name: "Watermelon HTTP client"
description: "Perform HTTP requests within your workflow. Supports GraphQL!"
author: "Camilo Garcia La Rotta"
inputs:
  url:
    description: Endpoint to query
    default: "https://api.github.com"
  method:
    description: HTTP method
    default: get
  headers:
    description: HTTP custom headers
  data:
    description: HTTP request payload
  graphql:
    description: GraphQL query or mutation to execute. If defined, the 'data' field is automatically populated with the this payload and the 'method' is set to POST
  variables:
    description: variables for a GraphQL mutation in JSON format
    default: '{}'
  operation_name:
    description: name of the entrypoint GraphQL operation if multiple are defined in `graphql`
  fail_fast:
    description: wether to fail upon error HTML responses (e.g. 400, 500)
    default: false
  verbose:
    description: wether to print info-level statements or not
    default: false
outputs:
  status:
    description: The status of the HTTP request
  headers:
    description: The response HTTP headers
  response:
    description: The raw query response body
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: 'aperture'
  color: 'green'
